#!/bin/bash


APP_PATH=/home/{{name}}/uwsgi/app{{secret}}

if [ -z $(grep "^{{name}}:" /etc/passwd) ]
then
	adduser --system --disabled-password {{name}}	
	chown -R {{name}}:{{name}} /home/{{name}}
	usermod -a -G {{name}} www-data
fi

virtualenv --no-site-packages /home/{{name}}/env

chmod +x /etc/init.d/uwsgi-{{name}}
chown -R {{name}}:{{name}} $APP_PATH

update-rc.d uwsgi-{{name}} defaults

/etc/init.d/nginx reload
/etc/init.d/uwsgi-{{name}} restart 

