#!/bin/bash


GIT_PATH=/home/{{user}}/{{name}}.git
APP_PATH=/home/{{user}}/deployed-apps/{{name}}

if [ -z `grep "^{{user}}:" /etc/passwd` ]
then
	yes '' | adduser --home /home/{{user}} --disabled-password {{user}}
	
	mkdir -p /home/{{user}}
	chown -R {{user}}:{{user}} /home/{{user}}
	usermod -a -G boatyard {{user}}
	usermod -a -G {{user}} www-data
fi

if [ ! -d "$APP_PATH/env" ]
then 
	virtualenv --no-site-packages $APP_PATH/env
fi

if [ ! -f "$GIT_PATH/HEAD" ]
then
	mv $GIT_PATH/hooks/post-update /tmp/{{random}}.git-post-update
	mkdir -p $GIT_PATH
	cd $GIT_PATH
	git init --bare
	git config core.worktree $APP_PATH/app{{secret}}
	git config core.bare false 
	git config receive.denycurrentbranch ignore
	mv /tmp/{{random}}.git-post-update $GIT_PATH/hooks/post-update
fi

chmod +x /etc/init.d/boatyard-{{name}}
chmod +x $GIT_PATH/hooks/post-update

mkdir -p /home/{{user}}/log/{{name}}
mkdir -p $APP_PATH/app{{secret}}

touch /var/log/boatyard/{{name}}.error
touch /var/log/boatyard/{{name}}.access
ln -s /var/log/boatyard/{{name}}.error /home/{{user}}/log/{{name}}/error.log
ln -s /var/log/boatyard/{{name}}.access /home/{{user}}/log/{{name}}/access.log

chown -R {{user}}:{{user}} $APP_PATH
chown -R {{user}}:{{user}} $GIT_PATH
chown {{user}}:{{user}} /var/log/boatyard/{{name}}.*

update-rc.d boatyard-{{name}} defaults

/etc/init.d/nginx reload
/etc/init.d/boatyard-{{name}} start 

