#! /bin/sh

### BEGIN INIT INFO
# Provides:          boatyard-{{name}}
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the boatyard-{{name}} web server
# Description:       starts boatyard-{{name}} using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC={{name}}

DAEMON=/etc/uwsgi/uwsgi26
PIDFILE=/var/run/boatyard-{{name}}.pid
SOCKFILE=/tmp/boatyard-{{name}}.sock
DAEMON_OPTS="--processes {{options.process}} --harakiri {{options.harakiri}} {{options.additional}} --disable-logging --master \
			--pidfile /var/run/boatyard-{{name}}.pid \
			--daemonize /dev/null \
			--socket /tmp/boatyard-{{name}}.sock \
			--home /home/{{user}}/deployed-apps/{{name}}/env \
			--chmod-socket --xmlconfig /home/{{user}}/deployed-apps/{{name}}/scripts/uwsgi.conf"

set -e

. /lib/lsb/init-functions

RUNUSER=$(id -nu)
if [ "$RUNUSER" = "{{user}}" ] 
then
	SUDO=
else
	SUDO="sudo -u {{user}}"
fi

touch $PIDFILE
chown -R {{user}}:{{user}} $PIDFILE

case "$1" in
  start)
	echo -n "Starting $DESC: "
	$SUDO start-stop-daemon --start --quiet \
		--pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS || true
	echo "boatyard-{{name}}."
	;;
  stop)
	echo -n "Stopping $DESC: "
	$SUDO start-stop-daemon --stop --signal INT --quiet \
		--pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS || true
	echo "boatyard-{{name}}."
	;;
  force-reload)
	echo -n "Force Reload $DESC: "
	kill -s TERM $(cat $PIDFILE) || true
	$SUDO start-stop-daemon --start --quiet \
		--pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS || true
	echo "boatyard-{{name}}."
	;;
  reload)
	echo -n "Reload $DESC: "
	kill -s HUP $(cat $PIDFILE) || true
	$SUDO start-stop-daemon --start --quiet \
		--pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS || true
	echo "boatyard-{{name}}."
	;;
  restart)
	echo -n "Restart $DESC: "
	$SUDO start-stop-daemon --stop --signal INT --quiet \
		--pidfile $PIDFILE || true
	sleep 5
	$SUDO start-stop-daemon --start --quiet \
		--pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS || true
	echo "boatyard-{{name}}."
	;;
  status)
	echo -n "Status $DESC: "
	kill -s USR1 $(cat $PIDFILE) || true
	tail -5 /tmp/boatyard-{{name}}.out
	echo "boatyard-{{name}}."
	;;
  *)
	echo "Usage: boatyard-{{name}} {start|stop|restart|force-reload|reload|status}" >&2
	exit 1
	;;
esac

exit 0
