#!/bin/bash


APP_PATH=/home/{{name}}

if [ -z `grep "^{{name}}:" /etc/passwd` ]
then
	yes '' | adduser --home /home/{{name}} --disabled-password {{name}}
	
	mkdir -p /home/{{name}}
	chown -R {{name}}:{{name}} /home/{{name}}
	usermod -a -G {{name}} www-data
fi

if [ ! -d "$APP_PATH/env" ]
then 
	virtualenv --no-site-packages $APP_PATH/env
fi


chmod +x /etc/init.d/uwsgi-{{name}}
ln -s /etc/nginx/sites-available/{{name}} /etc/nginx/sites-enabled/{{name}}
ln -s /var/log/www/{{name}} /home/{{name}}/log

chown -R {{name}}:{{name}} $APP_PATH

update-rc.d uwsgi-{{name}} defaults

/etc/init.d/nginx reload
/etc/init.d/uwsgi-{{name}} restart 

